#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mypy
Version  : 0.590
Release  : 6
URL      : https://github.com/python/mypy/archive/v0.590.tar.gz
Source0  : https://github.com/python/mypy/archive/v0.590.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT Python-2.0
Requires: mypy-bin
Requires: mypy-python3
Requires: mypy-python
Requires: typed-ast
Requires: typing
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : typed-ast
BuildRequires : typing

%description
ReadMe for pinfer
=================
Introduction
------------
Pinfer is tool for runtime type inference of variable types and
function signatures in Python programs. The inferred types are mostly
compatible with mypy types. It is intended for coming up with draft
types when migrating Python code to static typing, but it can also be
used as a code understanding or analysis tool.

%package bin
Summary: bin components for the mypy package.
Group: Binaries

%description bin
bin components for the mypy package.


%package python
Summary: python components for the mypy package.
Group: Default
Requires: mypy-python3

%description python
python components for the mypy package.


%package python3
Summary: python3 components for the mypy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mypy package.


%prep
%setup -q -n mypy-0.590

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523716046
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/lib/mypy/xml/mypy-html.css
/usr/lib/mypy/xml/mypy-html.xslt
/usr/lib/mypy/xml/mypy-txt.xslt
/usr/lib/mypy/xml/mypy.xsd

%files bin
%defattr(-,root,root,-)
/usr/bin/dmypy
/usr/bin/mypy
/usr/bin/stubgen

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
